require('dotenv').config();
const { getGitHubStats } = require('./github');
const { getETHGlobalEvents, getTalentCampaigns } = require('./hackathons');
const fs = require('fs');
const path = require('path');
const https = require('https');

const FREE_MODELS = [
  'moonshotai/kimi-k2.6:free',
  'google/gemma-4-31b-it:free',
  'google/gemma-4-26b-a4b-it:free',
  'nvidia/nemotron-3-super-120b-a12b:free',
  'poolside/laguna-m.1:free'
];

function requestModel(model, prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }]
    });
    const req = https.request({
      hostname: 'openrouter.ai',
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        'HTTP-Referer': 'https://github.com/alinasisi/base-builder-tools',
        'X-Title': 'Base Builder Tools'
      }
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (json.error || !json.choices || !json.choices[0]) {
            reject(new Error(json.error?.message || 'No response'));
            return;
          }
          resolve(json.choices[0].message.content);
        } catch(e) { reject(e); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function aiRequest(prompt) {
  for (const model of FREE_MODELS) {
    try {
      console.log(`Trying model: ${model}`);
      const result = await requestModel(model, prompt);
      console.log(`Success with: ${model}`);
      return result;
    } catch(e) {
      console.log(`Failed (${model}): ${e.message}`);
    }
  }
  return '*Analysis unavailable — all models failed*';
}

async function generateReport() {
  const date = new Date().toISOString().split('T')[0];
  console.log(`Generating report for ${date}...`);

  const github = await getGitHubStats();
  console.log('GitHub stats:', github);

  const campaigns = await getTalentCampaigns();
  const hackathons = await getETHGlobalEvents();

  const analysis = await aiRequest(
    `You are a Base ecosystem analyst. Write a short daily insight (150-200 words) for ${date} covering:
1. One interesting trend in Base/onchain builder space today
2. A practical tip for builders improving their Talent Protocol score
3. One actionable idea for a small Base project
Be specific, technical, and useful. No fluff. Format as markdown.`
  );

  const researchTopic = await aiRequest(
    `Generate a short research note (100-150 words) about one specific Base ecosystem topic for ${date}.
Pick from: DeFi protocol mechanics, NFT infrastructure, onchain identity, AI agents on Base, or creator tools.
Be specific with protocol names where relevant. Format as markdown.`
  );

  const report = `# Daily Builder Report — ${date}

## Ecosystem Analysis
${analysis}

---

## Research Note
${researchTopic}

---

## Live Metrics

### GitHub (alinasisi)
- Followers: ${github.followers || 'N/A'}
- Public Repos: ${github.repos || 'N/A'}
- Engagement Score: ${github.score || 'N/A'} → ${github.level || 'N/A'}

### Active Campaigns
${campaigns}

### Upcoming Hackathons
${hackathons}

---
*Auto-generated by [base-builder-tools](https://github.com/alinasisi/base-builder-tools)*
`;

  const dir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, `${date}.md`), report);
  console.log(`Report saved: reports/${date}.md`);

  const files = fs.readdirSync(dir)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .sort().reverse()
    .map(f => `- [${f.replace('.md','')}](${f})`);

  fs.writeFileSync(path.join(dir, 'README.md'),
    `# Builder Reports\n\nDaily Base ecosystem analysis.\n\n${files.join('\n')}\n`
  );

  console.log('Done!');
}

generateReport().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
