const { getGitHubStats } = require('./github');
const { getETHGlobalEvents, getTalentCampaigns } = require('./hackathons');
const fs = require('fs');
const path = require('path');
const https = require('https');

function openaiRequest(prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: 'gpt-4o-mini',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }]
    });
    const req = https.request({
      hostname: 'api.openai.com',
      path: '/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
      }
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          resolve(json.choices[0].message.content);
        } catch(e) { reject(e); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function generateReport() {
  const date = new Date().toISOString().split('T')[0];
  const github = await getGitHubStats();
  const campaigns = await getTalentCampaigns();
  const hackathons = await getETHGlobalEvents();

  const analysis = await openaiRequest(
    `You are a Base ecosystem analyst. Write a short daily insight (150-200 words) for ${date} covering:
1. One interesting trend in Base/onchain builder space today
2. A practical tip for builders improving their Talent Protocol score
3. One actionable idea for a small Base project
Be specific, technical, and useful. No fluff. Format as markdown.`
  );

  const researchTopic = await openaiRequest(
    `Generate a short research note (100-150 words) about one specific Base ecosystem topic for ${date}.
Pick from: DeFi protocol mechanics, NFT infrastructure, onchain identity, AI agents on Base, or creator tools.
Be specific with protocol names where relevant. Format as markdown.`
  );

  const report = `# Daily Builder Report — ${date}

## Ecosystem Analysis
${analysis}

---

## Research Note
${researchTopic}

---

## Live Metrics

### GitHub (alinasisi)
- Followers: ${github.followers}
- Public Repos: ${github.repos}
- Engagement Score: ${github.score} → ${github.level}

### Active Campaigns
${campaigns}

### Upcoming Hackathons
${hackathons}

---
*Auto-generated by [base-builder-tools](https://github.com/alinasisi/base-builder-tools)*
`;

  const dir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir);
  fs.writeFileSync(path.join(dir, `${date}.md`), report);

  const indexLines = fs.readdirSync(dir)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .sort().reverse()
    .map(f => `- [${f.replace('.md','')}](${f})`);

  fs.writeFileSync(path.join(dir, 'README.md'),
    `# Builder Reports\n\nDaily Base ecosystem analysis.\n\n${indexLines.join('\n')}\n`
  );

  console.log(`Report saved: reports/${date}.md`);
}

generateReport().catch(console.error);
